// physicalContradictionPrinciples.js
// Matriz de Principios Inventivos para Contradicciones Físicas basada en S. Litvin (1993)

const physicalContradictionPrinciples = {
    separationInSpace: {
        strategy: "Separation in space",
        description: "Separate contradictory demands in space",
        principles: [
            {
                number: "1",
                name: "Segmentation",
                description: "Divide an object into independent parts or increase degree of fragmentation",
                example: "LED bulb with multiple small diodes instead of single filament"
            },
            {
                number: "2",
                name: "Taking away",
                description: "Extract a disturbing part or property from an object",
                example: "Pencil with separable lead that can be reused"
            },
            {
                number: "3",
                name: "Local conditions",
                description: "Provide transition from homogeneous to heterogeneous structure",
                example: "Socks with anti-slip knobs only on the bottom side"
            },
            {
                number: "4",
                name: "Asymmetry",
                description: "Replace symmetrical form with asymmetrical form",
                example: "Asymmetrical car tire with sidewall reinforcement for better protection"
            },
            {
                number: "7",
                name: "Nesting",
                description: "Contain an object inside another, which in turn is placed inside a third object",
                example: "Foldable trekking cup for space-saving transport"
            },
            {
                number: "17",
                name: "Transition into new dimension",
                description: "Remove problems of moving in a line by allowing movement along a plane or in space",
                example: "Multi-story arrangement instead of single-story arrangement"
            }
        ]
    },
    separationInTime: {
        strategy: "Separation in time", 
        description: "Separate contradictory demands in time",
        principles: [
            {
                number: "15",
                name: "Dynamics, adjustability",
                description: "Make characteristics automatically adjust for optimal performance at each stage",
                example: "Modern office chairs adjustable to individual requirements"
            },
            {
                number: "34", 
                name: "Rejection and regeneration",
                description: "After completing its function, reject or modify an element; restore used up parts",
                example: "Rechargeable battery that can be regenerated by recharging"
            },
            {
                number: "10",
                name: "Prior action", 
                description: "Carry out required action in advance, in full or in part",
                example: "Coffee capsules with pre-portioned coffee for single cup"
            },
            {
                number: "9",
                name: "Prior counteraction",
                description: "If necessary to carry out action, consider counteraction in advance",
                example: "Child-resistant bottle caps requiring simultaneous pinching and turning"
            },
            {
                number: "11",
                name: "Beforehand compensation", 
                description: "Compensate for low reliability by countermeasures taken in advance",
                example: "Toothbrush with soft silicone head to protect sensitive gums"
            }
        ]
    },
    separationInRelation: {
        strategy: "Separation in relation",
        description: "Separate contradictory demands in relation to conditions", 
        principles: [
            {
                number: "40",
                name: "Composite materials",
                description: "Replace homogeneous material with composite one",
                example: "Carbon fiber reinforced plastic for strength and light weight"
            },
            {
                number: "31",
                name: "Porous materials",
                description: "Make object porous or use additional porous elements",
                example: "Foam materials with air containments for cushion purposes"
            },
            {
                number: "32",
                name: "Optical property changes",
                description: "Change color, transparency or emissivity properties",
                example: "pH test strips changing color based on liquid acidity"
            },
            {
                number: "3",
                name: "Local conditions",
                description: "Place each part under conditions most favourable for its operation",
                example: "Pipe manufacturing with cooled exterior and hot interior for guidance"
            },
            {
                number: "19",
                name: "Periodic action",
                description: "Replace continuous action with periodic one; use pauses between impulses",
                example: "Jack-hammer using periodic movements to gradually remove material"
            },
            {
                number: "17",
                name: "Transition into new dimension",
                description: "Utilize opposite side of surface; project on neighboring areas",
                example: "Wireless presenter mouse with controls on underside for presentations"
            }
        ]
    },
    separationInSystemLevel: {
        strategy: "Separation in system level",
        description: "Separate contradictory demands at different system levels",
        principles: [
            {
                number: "1",
                name: "Segmentation",
                description: "Make system easy to put together and take apart",
                example: "Replaceable head toothbrush reducing waste"
            },
            {
                number: "5",
                name: "Merging",
                description: "Combine in space or time homogeneous objects or operations",
                example: "Multihull watercraft combining multiple hulls for higher speed"
            },
            {
                number: "33",
                name: "Homogeneity",
                description: "Make objects interact with primary object of same material",
                example: "Biodegradable garbage bags that can be composted with contents"
            },
            {
                number: "12",
                name: "Equipotentiality",
                description: "Change conditions to eliminate need to work against potential field",
                example: "Roller cabinets with casters for easy positioning"
            }
        ]
    },
    satisfyContradictoryDemands: {
        strategy: "Satisfy contradictory demands",
        description: "Satisfy both contradictory demands through system transition",
        principles: [
            {
                number: "36",
                name: "Phase transition",
                description: "Use phenomena occurring during phase transitions",
                example: "Shape memory metal returning to original shape when heated"
            },
            {
                number: "37",
                name: "Thermal expansion",
                description: "Use thermal expansion or contraction of materials",
                example: "Heat-shrink tubing shrinking radially when heated for insulation"
            },
            {
                number: "28",
                name: "Replace mechanical system with fields",
                description: "Replace mechanical system by optical, acoustical or electromagnetic fields",
                example: "Keyless entry systems using radio signals instead of mechanical keys"
            },
            {
                number: "35",
                name: "Changing properties",
                description: "Change aggregate state, concentration, temperature or pressure",
                example: "Glue stick that is soft for application then hardens for adhesion"
            },
            {
                number: "38",
                name: "Use strong oxidizers",
                description: "Replace normal air with enriched air or oxygen",
                example: "Oxygen converter using pure oxygen to make low-carbon steel"
            },
            {
                number: "39",
                name: "Inert environment",
                description: "Replace normal environment with inert one; carry out process in vacuum",
                example: "Incandescent bulbs filled with inert gas to prevent filament burning"
            }
        ]
    },
    bypassContradictoryDemands: {
        strategy: "Bypass contradictory demands",
        description: "Bypass the need to satisfy contradictory demands",
        principles: [
            {
                number: "25",
                name: "Self service",
                description: "Make object service itself and carry out supplementary operations",
                example: "Solar-powered calculator using daylight to preserve batteries"
            },
            {
                number: "6",
                name: "Multi-functionality",
                description: "Have object perform multiple functions, eliminating need for other objects",
                example: "Swiss Army knife combining functions of various tools"
            },
            {
                number: "13",
                name: "The other way round",
                description: "Implement opposite action; turn process upside down",
                example: "Escalators with moving steps requiring no effort to move"
            }
        ]
    }
};

// Función auxiliar para obtener ejemplos de estrategias
function getPhysicalContradictionExample(relationship) {
    const examples = {
        separationInSpace: "Using asymmetrical card slots to ensure proper insertion orientation, separating the requirement for easy insertion from the requirement for correct orientation.",
        separationInTime: "Piezoelectric lighters that generate spark and open gas valve in one action, separating the ignition sequence in time.",
        separationInRelation: "Sandwich panels with porous foam filling between outer layers, providing durability with minimum weight through material relationship.",
        separationInSystemLevel: "Traffic light with segmented pole elements for easy repair, separating maintenance requirements at different system levels.",
        satisfyContradictoryDemands: "Heat packs using phase transition of gel to provide warmth without external heat source, satisfying both heating and portability demands.",
        bypassContradictoryDemands: "Digital clocks replacing mechanical clockwork, bypassing the need for mechanical timekeeping altogether."
    };
    return examples[relationship] || "No example available.";
}

// Exportar para uso en otros módulos (si es necesario)
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { physicalContradictionPrinciples, getPhysicalContradictionExample };
}